# -*- mode: ruby -*-
# vi: set ft=ruby :
hosts = {
 "n1" => "192.168.56.18",
 "n2" => "192.168.56.19",
}
Vagrant.configure("2") do |config|
 # всегда используем небезопасный ключ Vagrant
 config.ssh.insert_key = false
 # перенаправляем ssh-агент, чтобы получить легкий доступ к разным узлам
 config.ssh.forward_agent = true
 check_guest_additions = false
 functional_vboxsf = false
 config.vm.box = "bento/ubuntu-22.04"
 config.ssh.password = 'vagrant'
hosts.each do |name, ip|
 config.vm.hostname = name
 config.vm.define name do |machine|
  machine.vm.network :private_network, ip: ip
  machine.vm.hostname = name
  machine.vm.provider "virtualbox" do |v|
   v.memory = 2048
   v.name = name
  end
 end
end
end
